[package]
name = "factorsvg"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
clap = { version = "4", features = ["derive"] }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.16.0", features = [
    "v4",
]}

